### ISSUE TITLE
Synthesizer

### ISSUE THREAD

**Issue by gktval** [bvavra/MIDI_Accordion#13]
Awesome project! Thank you so much. This has inspired me to create my own. Think I'll try to do it with an MSP430 instead of Arduino, though.

Question: Have you found a synthesizer with various accordion sounds? I was thinking about adding buttons for the registers, but would like to find a program with a library that can support them. For example a clarinet, musette, master, etc.

**Comment by bvavra** [comment]
Hiyo, thanks for your interest in this project!

I personally use Reason as my primary driver of virtual instrument sounds, and I've since implemented a button pad that can be configured to change "registers" (if you will), though I personally like to explore other unnatural, more "synthy" sounds for my MIDI accordion since my acoustic accordion covers the natural accordion tone well enough (see my [YouTube channel](https://www.youtube.com/playlist?list=PLwO5aXJYrMqShhljt1XpOR_GsGuI3mNtk) for various examples of my MIDI accordion in action).

However, if you're looking for an authentic accordion around for your virtual instrument, I highly recommend the [Accordions 2 Sample Pack](https://www.bigfishaudio.com/Accordions-2), which I believe to be the gold standard for providing the most realistic-sounding accordion samples for MIDI instruments.

I also want to clarify that my project sends the MIDI to the PC and the PC is what generates the sound accordingly - i.e., the accordion is just a MIDI controller and does not produce any sound on its own.  Of course, the project could be modified to include speakers and samples on the instrument itself, but in that case you're on your own to figure out the details of how to make that work.
