### ISSUE TITLE
5 din midi

### ISSUE THREAD

**Issue by denia85** [bvavra/MIDI_Accordion#4]
Thank you for your project. And it is possible to implement somehow connection through 5 din midi

**Comment by bvavra** [comment]
Hiyo,

Yes, it is possible to use a standard MIDI cable instead of USB.  I mentioned this briefly on my [MIDI Playback](http://bvavra.github.io/MIDI_Accordion/midi-playback/) section of my in-depth guide: you can follow the [Arduino MIDI tutorial](https://www.arduino.cc/en/Tutorial/Midi) to attach a MIDI port to your Arduino's serial pin to transmit MIDI data from the Arduino through the MIDI port.  I've not done this with my project, so I haven't personally tested it with my MIDI accordion code, but I did research it as a viable option, and the existing links I posted in my MIDI guide should serve as a good starting point.
